config/routes.rb
Rails.application.routes.draw do
  
  get 'rankings/index'
  root to: 'toppages#index'
  devise_for :users
  resources :users do
    member do
      get :followings
      get :followers
      get :read
    end
  end
  
  resources :books, only: [:index, :show, :create, :new, :update, :destroy] do
    member do
      post :add
      post :add_read
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :rankings, only: [:index]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  description            :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  name                   :string(255)      default(""), not null
#  profile_img            :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :userbooks
  has_many :books, through: :userbooks, source: :book
  has_many :reading_book, -> { where "status = 1"}, through: :userbooks, source: :book
  has_many :have_read_book, -> { where "status = 2"}, through: :userbooks, source: :book
         
         
  validates :name, presence: true
  validates :description, length: { maximum: 140 }
  
  mount_uploader :profile_img, ImageUploader
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  
  
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.all.order(id: 'desc').limit(20)
  end
  
  def show
    @user = User.find_by(id: params[:id])
    counts(@user)
    @all_books = @user.books.all
    @reading_book = @user.reading_book.all
    
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:success] = 'プロフィールを更新しました。'
      redirect_to user_path
    else
      flash[:danger] = 'プロフィールを更新できませんでした'
      redirect_to edit_user_path
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
    counts(@user)
  end
  
  
  def read  
    @user = User.find_by(id: params[:id])
    counts(@user)
    @have_read_book = @user.have_read_book.all
  end
  private
  
  def user_params
    params.require(:user).permit(:profile_img, :description)
  end
  
  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to root_path unless @user == current_user
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show_book_wrapper.html.erb
<div class="book_container row">
  <% reading_book.each do |book| %>
    <div class='book_item list_item'>
      <figure class='book_image book_item_image'>
        <%= link_to (image_tag(book.image_url)), book_path(book.id) %>
      </figure>
    </div>
  <% end %>
</div>

app/views/users/_show_top_wrapper.html.erb
<div class='container'>
  <div class="user_info d-sm-flex row">
    <div class="info_left col-4">
      <div class='user_info_img'>
        <%= render 'user_image', user: @user%>
      </div>
    </div>
    <div class="info_right col-8">
      <div class='info_top_wrapper d-sm-flex'>
        <div class='user_info_name'>
          <%= @user.name %>
        </div>
        <div class='user_info_following_btn'>
          <% if current_user == user %>
            <%= link_to 'プロフィールの編集', edit_user_path, class: 'btn btn-outline-secondary btn-sm profile_btn' %> 
          <% else %>
            <!--自分のプロフィールでは編集ボタンの表示-->
            <%= render 'relationships/follow_button', user: @user %>
          <% end %>
        </div>
      </div>
      
      <div class="info_middle_wrapper d-sm-flex">
        <div class="user_info_count_follow"><%= @count_followings %> フォロー</div>
        <div class="user_info_count_follower"><%= @count_followers %> フォワー</div>
      </div>
      
      
      <div　class='user_info_self_description'>
        <div class='description'>
          <pre><%= @user.description %></pre>
        </div>
      </div>
    </div>
    
  </div>

</div>

app/views/users/_user_image.html.erb
<% if user.profile_img? %>
  <%= image_tag user.profile_img.thumb.url %>
<% else %>
  <i class="far fa-user-circle icon"></i>
<% end %>

app/views/users/edit.html.erb
  <div class='edit_user'>
    <h3>プロフィール編集</h3>
    <hr></hr>
     <%= form_with(model: @user, location: true) do |f| %>
      <div class='edit_image_container'>
        <% if @user.profile_img? %>
           <%= image_tag @user.profile_img.thumb.url %>
        <% else %>
           <i class="far fa-user-circle icon"></i>
        <% end %>
      </div>   
      <div class='edit_btn_container form-group'>
        <button type="file" class="btn">
          <%= f.file_field :profile_img %>
        </button>
      </div>
      <div class='form-group textarea'>
        <%= f.label '自己紹介　(140字以内)'%>
        <%= f.text_area :description, class: 'form-control text_form', cols: '20', rows: '5', wrap: 'hard', maxlength: '140' %>
      </div>
         
   　　<%= f.submit '更新する', class: 'btn btn-primary' %>
   <% end %>
  </div>

app/views/users/index.html.erb
<div class='users_page'>
  <div>
    <div class='new_user_title'>新着ユーザー</div>
    <hr></hr>
    <div class='user_content'>
      <div class='user_box'>
        <div class='user_container row'>
          <% @users.each do |user| %>
            
              <div class='col-lg-3 col-md-4 user_box'>
                <div class='user_info_img'>
                  <% if user.profile_img? %>
                    <%= link_to (image_tag(user.profile_img.thumb.url)), user_path(user.id)%>
                  <% else %>
                    <%= link_to "\uf2bd", user_path(user.id), class: 'far fa-user-circle user_icon'%>
                  <% end %>
                </div>
                <h5><%= user.name %></h5>
              </div>
              
           
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/read.html.erb
<%= render 'show_top_wrapper', user: @user %>

<hr>
<ul class="nav nav-pills justify-content-center">
  <li class="nav-item">
    <a class="nav-link nav-reading <%= 'active' if current_page?(user_path(@user)) %>" href="<%= user_path(@user)%>">読書中</a>
  </li>
  <li class="nav-item">
    <a class="nav-link nav-read <%= 'active' if current_page?(read_user_path(@user)) %>" href="<%= read_user_path(@user) %>">読了</a>
  </li>
</ul>
<div class="register_books">
 <%= render 'show_book_wrapper', reading_book: @have_read_book %>
</div>

app/views/users/show.html.erb
<%= render 'show_top_wrapper', user: @user %>

<hr>
<ul class="nav nav-pills justify-content-center">
  <li class="nav-item">
    <a class="nav-link nav-reading <%= 'active' if current_page?(user_path(@user)) %>" href="<%= user_path(@user)%>" href="<%= user_path(@user)%>">読書中</a>
  </li>
  <li class="nav-item">
    <a class="nav-link nav-read <%= 'active' if current_page?(read_user_path(@user)) %>" href="<%= read_user_path(@user) %>">読了</a>
  </li>
</ul>
<div class="register_books">
 <%= render 'show_book_wrapper', reading_book: @reading_book %>
</div>