config/routes.rb
Rails.application.routes.draw do
  
  get 'rankings/index'
  root to: 'toppages#index'
  devise_for :users
  resources :users do
    member do
      get :followings
      get :followers
      get :read
    end
  end
  
  resources :books, only: [:index, :show, :create, :new, :update, :destroy] do
    member do
      post :add
      post :add_read
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :rankings, only: [:index]
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :bigint           not null, primary key
#  author     :string(255)
#  image_url  :string(255)
#  item_url   :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Book < ApplicationRecord
    has_many :users, through: :userbook, source: :user
    has_many :userbooks
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order(id: 'desc').limit(20)
  end

  def show
    @book = Book.find(params[:id])
    @status_book = current_user.userbooks.find_by(book_id: @book.id)
  end

  
  def new
    @book = Book.new
    @books = []
    return unless params.key?(:title)
      
    if params[:title].present? && params[:title].size > 1
      results = RakutenWebService::Books::Book.search(title: params[:title])
      
      results.each do |result|
        book = Book.find_or_initialize_by(read(result))
        @books << book
     end
    elsif params[:title].present? && params[:title].size == 1
      flash.now[:notice] = 'キーワードは2文字以上入力してください'
    else
      flash.now[:notice] = 'キーワードを入力してください'
    end
  end
  
  def create
    @title = params[:book][:title]
    @author = params[:book][:author]
    @image_url = params[:book][:image_url]
    @item_url = params[:book][:item_url]
    
    book = Book.find_or_initialize_by({
      title: @title,
      author: @author,
      image_url: @image_url,
      item_url: @item_url
    })
    
    if book.persisted?
      book_data = Book.find_by(item_url: book.item_url)
      current_user.register_book(book_data)
      redirect_to user_path(current_user.id)
    else
      book.save
      current_user.register_book(book)
      redirect_to user_path(current_user.id)
    end

  end
  
  def update
    book = Book.find(params[:id])
    userbook = current_user.userbooks.find_by(book_id: book.id)
    
    if userbook.status == 1
      userbook.status = 2
      if userbook.save
        flash[:success] = 'ステータスを変更しました'
        redirect_back(fallback_location: root_path)
      else
        flash.now[:danger] = 'ステータス変更できませんでした'
        render :show
      end
    elsif userbook.status == 2
      userbook.status = 1
      userbook.save
      if userbook.save
        flash[:success] = 'ステータスを変更しました'
        redirect_back(fallback_location: root_path)
      else
        flash.now[:danger] = 'ステータス変更できませんでした'
        render :show
      end
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    userbook = current_user.userbooks.find_by(book_id: book.id)
    
    if userbook.delete
      flash[:success] = '本棚から削除しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '削除できませんでした'
      render :show
    end
  end
  
  def add
    book = Book.find(params[:id])
    if current_user.register_book(book)
      flash[:success] = '本棚に追加しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '本棚に追加できませんでした'
      render :show
    end
  end
 
  private
  
  def set_book
    book = Book.find(params[:id])
  end
  
  
end

app/views/books/_add_book.html.erb
<%= form_with(model: @book, method: :post) do |f| %>
  <%= f.hidden_field :title, value: book.title %>
  <%= f.hidden_field :author, value: book.author %>
  <%= f.hidden_field :image_url, value: book.image_url %>
  <%= f.hidden_field :item_url, value: book.item_url %>
  <% if current_user.books.find_by(item_url: book.item_url) %>
    <button class='btn btn-danger add_btn'>追加済み</button>
  <% else%>
    <%= f.submit '本棚に追加', class: 'btn btn-primary add_btn' %>
  <% end %>
<% end %>

app/views/books/_book_list.html.erb
  <% @books.each do |book| %>
    <div class="list row">
        <% if book.image_url %>
          <%= link_to (image_tag(book.image_url)), book.item_url, class: 'col-md-3 book_search_image' %>
        <%end%>
        <div class="book_infomation col-md-9">
          <div class="book_title">
            <%= book.title %>
          </div>
          <div class="book_author">
            <%= book.author %>
          </div>
          <%= render 'add_book', book: book %>
        </div>
        
    </div>
  <% end %>

app/views/books/_delete_button.html.erb
<% if current_user.registered_book?(@book) %>
  <%= form_with(model: @book, local: true, method: :delete) do |f| %>
    <%= f.hidden_field :id, :value => @book.id %>
    <%= f.submit '本棚から削除', class: 'btn btn-danger delete'%>
  <% end %>
<% end %>

app/views/books/_status.html.erb
<% if current_user.registered_book?(@book) && @status_book.status == 1 %>
  <span class='badge badge-info'>読書中</span>
<% elsif current_user.registered_book?(@book) && @status_book.status == 2 %>
  <span class='badge badge-success'>読了</span>
<% else %>
  <span class='badge badge-secondary'>未登録</span>
<% end %>

app/views/books/_status_button.html.erb
<%= form_with(model: @book, lacal: true, method: :patch) do |f| %>
  <%= f.hidden_field :id, :value => @book.id %>
  <% if @status_book.status == 1 %>
    <%= f.submit '読了に変更', class: 'btn btn-primary status'%>
  <% elsif @status_book.status == 2 %>
    <%= f.submit '読書中に変更', class: 'btn btn-primary status'%>
  <% end %>
<% end %>

app/views/books/add_read_book.html.erb
<%= form_with(url: add_read_book_path, local: true, method: :post) do |f|%>
  <%= f.hidden_field :title, value: book.title %>
  <%= f.hidden_field :author, value: book.author %>
  <%= f.hidden_field :image_url, value: book.image_url %>
  <%= f.hidden_field :item_url, value: book.item_url %>
  <% unless current_user.books.find_by(item_url: book.item_url) %>
    <%= f.submit '読了', class: 'btn btn-primary add_btn' %>
  <% end %>
<% end %>


<!--ステータスをつけて保存したい-->

app/views/books/index.html.erb
<div class='books_page'>
  <div>
    <div class='new_user_title'>新規登録本</div>
    <hr></hr>
    <div class='book_content'>
      <div class='book_boxs'>
        <div class='book_container_index row'>
          <% @books.each do |book| %>
            
              <div class='col-lg-3 col-md-4 book_box'>
                <div class='book_info_img'>
                
                    <%= link_to (image_tag(book.image_url)), book_path(book.id)%>
                 
                </div>
                <h5><%= book.title %></h5>
              </div>
              
           
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="search ">
  <div class="title">
    <h1>Rakubooks</h1>
  </div>
    
    <div class="search-box">
      <%= form_with(url: new_book_path, method: :get, local: true) do |f|%>
        <div class='form-group'>
          <%= f.text_field :title, class: 'form', placeholder: '　本のタイトル' %>
          <%= f.submit "\uf002", class: 'form-btn btn btn-primary fa' %>
        </div>
      <% end %>
    </div>
 
  <div class='search_title'>
      <h2>検索結果</h2>
  </div>
  <hr></hr>
  <div class="search_result">
    <div id='book_list'>
       <%= render partial: 'book_list' %>
    </div>
  </div>
  
</div>

app/views/books/search.html.erb
<div class="search">
  <div class='search_content'>
    <h1>Rakubooks</h1>
    <div class="search-box">
      <%= form_with(url: search_books_path, method: :get, local: true) do |f|%>
        <div class='form-group'>
        <%= f.text_field :keyword, class: 'form-controll' %>
        <%= f.submit '検索', class: 'form-controll btn btn-primary' %>
        </div>
      <% end %>
    </div>
    <h2>検索結果</h2>
    <div id='book_list'>
       <%= render partial: 'book_list' %>
    </div>
  </div>
 
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='book_page'>
    <div class='book_summary'>
      <div class="book_container_show d-md-flex">
        <div class="book_image">
          <%= link_to (image_tag(@book.image_url)), @book.item_url %>
        </div>
        <div class="book_info">
          <div class="book_title">
            <%= @book.title %>
          </div>
          <div>著者</div>
          <div class="book_author">
            <%= @book.author %>
          </div>
          <div class='mt-2'>ステータス：<%= render 'status' %></div>
          
        </div>
      </div>
      <div class="buttons d-md-flex justify-content-end">
        <% if current_user.registered_book?(@book) %>
          <%= render 'status_button' %>
          <%= render 'delete_button' %>
        <% else %>
          <%= form_with(url: add_book_path, local: true, method: :post) do |f|%>
            <%= f.hidden_field :id, :value => @book.id %>
            <%= f.submit '本棚に追加', class: 'btn btn-primary add' %>
          <% end %>  
        <% end %>
      </div>
    </div>
  </div>
</div>