config/routes.rb
Rails.application.routes.draw do
  
  get 'rankings/index'
  root to: 'toppages#index'
  devise_for :users
  resources :users do
    member do
      get :followings
      get :followers
      get :read
    end
  end
  
  resources :books, only: [:index, :show, :create, :new, :update, :destroy] do
    member do
      post :add
      post :add_read
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :rankings, only: [:index]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @users = User.all.order(id: 'desc').limit(4)
    @books = Book.all.order(id: 'desc').limit(4)
    @books_rank = Book.find(Userbook.group(:book_id).order('count(book_id) desc').limit(4).pluck(:book_id))
  end
end

app/views/toppages/_book.html.erb
<%= render 'book_container', books: @books%>
<div class='more_users row'>
  <div class='offset-sm-10 col-sm-2'>
    <%= link_to "もっとみる　\uf101", books_path, class: 'fas search-more' %>
  </div>
</div>

app/views/toppages/_book_container.html.erb
<div class='book-container row'>
  <% books.each do |book| %>
      <div class='col-sm-6 col-md-4 col-lg-3 col-6 user-box'>
        <div class='book-info-img'>
          <%= link_to (image_tag(book.image_url)), book_path(book.id) %>
        </div>
        <h5 class='pt-4 top-books-title'><%= book.title %></h5>
      </div>
  <% end %>
</div>

app/views/toppages/_book_rank.html.erb
<%= render 'book_container', books: @books_rank%>
<div class='more_users row'>
  <div class='offset-sm-10 col-sm-2'>
    <%= link_to "もっとみる　\uf101", rankings_path, class: 'fas search-more' %>
  </div>
</div>

app/views/toppages/_search_more.html.erb
<div class='more_users row'>
  <div class='offset-sm-10 col-sm-2'>
    <%= link_to "もっとみる　\uf101", users_path, class: 'fas search-more' %>
  </div>
</div>

app/views/toppages/_top.html.erb
<div class='top-wrapper col'>
  <div id="header-title-box"><span id='header-title'>&nbsp;Design<br>&nbsp;Your<br>&nbsp;Bookshelf</span></div>
  <div id='header-login-box'>
    <% unless user_signed_in? %>
      <%= link_to new_user_session_path, class: 'btn', id: 'header-login-btn' do %>
        <span>Login</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/toppages/_user.html.erb
<div class='user_container row'>
  <% users.each do |user| %>
      <div class='user_box col-lg-2 offset-lg-1 col-md-5 offset-md-1 col-sm-12'>
        <div class="top-user-image-box">
          <% if user.profile_img? %>
            <%= link_to (image_tag(user.profile_img.thumb.url)), user_path(user.id), class: 'top-user-image'%>
          <% else %>
            <%= link_to "\uf2bd", user_path(user.id), class: 'far fa-user-circle', id: 'user-icon'%>
          <% end %>
        </div>
        <h5 id='top-user-name'><%= user.name %></h5>
      </div>
  <% end %>
</div>
<%= render 'search_more' %>

app/views/toppages/index.html.erb
<header class="">
  <%= render 'top' %>
</header>

<main-content>
  <div class='new_user_container'>
    <h4 id='top-user-title'><i class="fas fa-users"></i>  新規登録ユーザー</h4>
    <hr>
      <%= render 'user', users: @users %>
    <hr>
  </div>
  
  
  <div class="new_register_book">
    <h4 class="top-title"><i class="fas fa-book"></i>  新規登録本</h4>
    <hr>
      <%= render 'book', books: @books %>
    <hr>
  </div>
  
  <div class="new_register_book">
    <h4 class="top-title"><i class="fas fa-book"></i>  書籍登録数ランキング</h4>
    <hr>
      <%= render 'book_rank', books: @books_rank %>
    <hr>
  </div>
</main-content>